import { ScratchcardData, WebsiteLink } from './types';

export const INITIAL_RASPADINHAS: ScratchcardData[] = [
  {
    id: '1',
    customId: 'RASP-PT-001',
    frontUrl: 'https://placehold.co/600x600/1f2937/white?text=Super+Pe+de+Meia',
    backUrl: 'https://placehold.co/600x400/1f2937/white?text=Verso+Super+Pe+de+Meia',
    gameName: 'Super Pé de Meia',
    gameNumber: '105',
    releaseDate: '2023-05-12',
    size: '10x15cm',
    values: '5€, 10€, 50€, 1000€',
    state: 'MINT',
    country: 'Portugal',
    region: 'Continente', // Added region
    continent: 'Europa',
    category: 'raspadinha',
    aiGenerated: false,
    createdAt: Date.now() - 100000,
  },
  {
    id: '2',
    customId: 'RASP-ES-042',
    frontUrl: 'https://placehold.co/600x800/881337/white?text=Millonario',
    backUrl: 'https://placehold.co/600x400/1f2937/white?text=Verso+Millonario',
    gameName: 'Millonario',
    gameNumber: '502',
    releaseDate: '2022-11-01',
    size: '15x20cm',
    values: '10€, 20€, 500€, 1.000.000€',
    state: 'MUESTRA',
    country: 'Espanha',
    region: 'Nacional', // Added region
    continent: 'Europa',
    category: 'raspadinha',
    aiGenerated: true,
    createdAt: Date.now() - 200000,
  },
  {
    id: '3',
    customId: 'RASP-US-889',
    frontUrl: 'https://placehold.co/800x600/1e3a8a/white?text=Lucky+7s',
    gameName: 'Lucky 7s',
    gameNumber: '777',
    releaseDate: '2024-01-15',
    size: '4x4in',
    values: '$1, $7, $77, $777',
    state: 'VOID',
    country: 'EUA',
    continent: 'América',
    category: 'raspadinha',
    aiGenerated: true,
    createdAt: Date.now() - 300000,
  },
  {
    id: '4',
    customId: 'RASP-IT-202',
    frontUrl: 'https://placehold.co/600x600/065f46/white?text=Turista+per+Sempre',
    gameName: 'Turista per Sempre',
    gameNumber: '304',
    releaseDate: '2021-08-20',
    size: '12x18cm',
    values: '5€, 10€, 200€, 50.000€',
    state: 'CAMPIONE',
    country: 'Itália',
    continent: 'Europa',
    category: 'raspadinha',
    aiGenerated: true,
    createdAt: Date.now() - 400000,
  },
  {
    id: '5',
    customId: 'RASP-JP-999',
    frontUrl: 'https://placehold.co/500x500/7c2d12/white?text=Anime+Scratch',
    gameName: 'Anime Scratch',
    gameNumber: '101',
    releaseDate: '2023-12-01',
    size: '10x10cm',
    values: '¥100, ¥500, ¥10000',
    state: 'MINT',
    country: 'Japão',
    continent: 'Ásia',
    category: 'raspadinha',
    aiGenerated: true,
    createdAt: Date.now() - 50000,
  },
  {
    id: '6',
    customId: 'RASP-DE-001',
    frontUrl: 'https://placehold.co/600x600/eab308/black?text=Bayern+Gluck',
    gameName: 'Bayern Glück',
    gameNumber: '101',
    releaseDate: '2023-01-01',
    size: '10x10cm',
    values: '5€',
    state: 'MINT',
    country: 'Alemanha',
    region: 'Baviera',
    continent: 'Europa',
    category: 'raspadinha',
    aiGenerated: true,
    createdAt: Date.now() - 10000,
  }
];

// Based on European Lotteries Members, World Lotteries & ALEA (Argentina)
export const EUROPEAN_LOTTERIES: Partial<WebsiteLink>[] = [
  // Global & Associations
  { name: "World Lottery Association (WLA)", url: "https://www.world-lotteries.org", country: "Mundo", category: "Global Organization" },
  { name: "ALEA (Argentina)", url: "https://www.alea.org.ar", country: "Argentina", category: "Association" },
  
  // Europe
  { name: "Santa Casa (SCML)", url: "https://jogossantacasa.pt", country: "Portugal", category: "Regular Member" },
  { name: "FDJ (La Française des Jeux)", url: "https://www.fdj.fr", country: "França", category: "Regular Member" },
  { name: "SELAE (Loterías y Apuestas)", url: "https://www.loteriasyapuestas.es", country: "Espanha", category: "Regular Member" },
  { name: "ONCE", url: "https://www.juegosonce.es", country: "Espanha", category: "Associate Member" },
  { name: "Lottomatica", url: "https://www.lottomatica.it", country: "Itália", category: "Regular Member" },
  { name: "Sisal", url: "https://www.sisal.it", country: "Itália", category: "Associate Member" },
  { name: "National Lottery (Allwyn)", url: "https://www.national-lottery.co.uk", country: "Reino Unido", category: "Regular Member" },
  { name: "Loterie Nationale", url: "https://www.loterie-nationale.be", country: "Bélgica", category: "Regular Member" },
  { name: "Swisslos", url: "https://www.swisslos.ch", country: "Suíça", category: "Regular Member" },
  { name: "Loterie Romande", url: "https://www.loro.ch", country: "Suíça", category: "Regular Member" },
  { name: "Lotto Bayern", url: "https://www.lotto-bayern.de", country: "Alemanha", category: "Regular Member" },
  { name: "WestLotto", url: "https://www.westlotto.de", country: "Alemanha", category: "Regular Member" },
  { name: "Danske Spil", url: "https://danskespil.dk", country: "Dinamarca", category: "Regular Member" },
  { name: "Norsk Tipping", url: "https://www.norsk-tipping.no", country: "Noruega", category: "Regular Member" },
  { name: "Svenska Spel", url: "https://www.svenskaspel.se", country: "Suécia", category: "Regular Member" },
  { name: "OPAP", url: "https://www.opap.gr", country: "Grécia", category: "Regular Member" },
  { name: "Österreichische Lotterien", url: "https://www.lotterien.at", country: "Áustria", category: "Regular Member" },
  { name: "Sazka", url: "https://www.sazka.cz", country: "Rep. Checa", category: "Regular Member" },
  { name: "Szerencsejáték Zrt.", url: "https://www.szerencsejatek.hu", country: "Hungria", category: "Regular Member" },
  { name: "Totalizator Sportowy", url: "https://www.lotto.pl", country: "Polónia", category: "Regular Member" },
  
  // Argentina (ALEA Members)
  { name: "Lotería de la Ciudad (LOTBA)", url: "https://www.loteriadelaciudad.gob.ar", country: "Argentina", category: "ALEA Member" },
  { name: "Lotería de la Provincia (Buenos Aires)", url: "https://www.loteria.gba.gov.ar", country: "Argentina", category: "ALEA Member" },
  { name: "Lotería de Córdoba", url: "https://www.loteriadecordoba.com.ar", country: "Argentina", category: "ALEA Member" },
  { name: "Lotería de Santa Fe", url: "https://www.loteriasantafe.gov.ar", country: "Argentina", category: "ALEA Member" },
  { name: "IAFAS (Entre Ríos)", url: "https://www.iafas.gov.ar", country: "Argentina", category: "ALEA Member" },
  { name: "IPLyC (Misiones)", url: "https://www.loteriademisiones.com.ar", country: "Argentina", category: "ALEA Member" },
  { name: "IPJyC (Mendoza)", url: "https://www.juegosymendoza.gov.ar", country: "Argentina", category: "ALEA Member" },
  { name: "Lotería de Río Negro", url: "https://www.loteriaderionegro.gov.ar", country: "Argentina", category: "ALEA Member" },
  { name: "Lotería del Chubut", url: "https://iss.chubut.gov.ar", country: "Argentina", category: "ALEA Member" }
];