import { ScratchcardData } from './types';

export const INITIAL_RASPADINHAS: ScratchcardData[] = [
  {
    id: '1',
    customId: 'RASP-PT-001',
    frontUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Scratch_card.jpg',
    backUrl: 'https://placehold.co/600x400/1f2937/white?text=Verso+Super+Pe+de+Meia',
    gameName: 'Super Pé de Meia',
    gameNumber: '105',
    releaseDate: '2023-05-12',
    size: '10x15cm',
    values: '5€, 10€, 50€, 1000€',
    state: 'MINT',
    country: 'Portugal',
    continent: 'Europa',
    aiGenerated: false,
    createdAt: Date.now() - 100000,
  },
  {
    id: '2',
    customId: 'RASP-ES-042',
    frontUrl: 'https://tse2.mm.bing.net/th?id=OIP.U5yZcTgwF6zC4_kC3wW2iQHaEK&pid=Api',
    backUrl: 'https://placehold.co/600x400/1f2937/white?text=Verso+Millonario',
    gameName: 'Millonario',
    gameNumber: '502',
    releaseDate: '2022-11-01',
    size: '15x20cm',
    values: '10€, 20€, 500€, 1.000.000€',
    state: 'MUESTRA',
    country: 'Espanha',
    continent: 'Europa',
    aiGenerated: true,
    createdAt: Date.now() - 200000,
  },
  {
    id: '3',
    customId: 'RASP-US-889',
    frontUrl: 'https://tse4.mm.bing.net/th?id=OIP.0C2_h-lq2x5sC6v8_yH2YQHaFj&pid=Api',
    gameName: 'Lucky 7s',
    gameNumber: '777',
    releaseDate: '2024-01-15',
    size: '4x4in',
    values: '$1, $7, $77, $777',
    state: 'VOID',
    country: 'EUA',
    continent: 'América',
    aiGenerated: true,
    createdAt: Date.now() - 300000,
  },
  {
    id: '4',
    customId: 'RASP-IT-202',
    frontUrl: 'https://tse3.mm.bing.net/th?id=OIP.wReJ1rQ4yv_yW5xZ_zH1ZAHaE8&pid=Api',
    gameName: 'Turista per Sempre',
    gameNumber: '304',
    releaseDate: '2021-08-20',
    size: '12x18cm',
    values: '5€, 10€, 200€, 50.000€',
    state: 'CAMPIONE',
    country: 'Itália',
    continent: 'Europa',
    aiGenerated: true,
    createdAt: Date.now() - 400000,
  },
  {
    id: '5',
    customId: 'RASP-JP-999',
    frontUrl: 'https://tse1.mm.bing.net/th?id=OIP.X1X3yC6zV9xB2nN3m4k5LwHaFj&pid=Api', // Placeholder
    gameName: 'Anime Scratch',
    gameNumber: '101',
    releaseDate: '2023-12-01',
    size: '10x10cm',
    values: '¥100, ¥500, ¥10000',
    state: 'MINT',
    country: 'Japão',
    continent: 'Ásia',
    aiGenerated: true,
    createdAt: Date.now() - 50000,
  }
];
