import { ScratchcardData } from './types';

export const INITIAL_RASPADINHAS: ScratchcardData[] = [
  {
    id: '1',
    customId: 'RASP-PT-001',
    frontUrl: 'https://placehold.co/600x600/1f2937/white?text=Super+Pe+de+Meia',
    backUrl: 'https://placehold.co/600x400/1f2937/white?text=Verso+Super+Pe+de+Meia',
    gameName: 'Super Pé de Meia',
    gameNumber: '105',
    releaseDate: '2023-05-12',
    size: '10x15cm',
    values: '5€, 10€, 50€, 1000€',
    state: 'MINT',
    country: 'Portugal',
    region: 'Continente', // Added region
    continent: 'Europa',
    category: 'raspadinha',
    aiGenerated: false,
    createdAt: Date.now() - 100000,
  },
  {
    id: '2',
    customId: 'RASP-ES-042',
    frontUrl: 'https://placehold.co/600x800/881337/white?text=Millonario',
    backUrl: 'https://placehold.co/600x400/1f2937/white?text=Verso+Millonario',
    gameName: 'Millonario',
    gameNumber: '502',
    releaseDate: '2022-11-01',
    size: '15x20cm',
    values: '10€, 20€, 500€, 1.000.000€',
    state: 'MUESTRA',
    country: 'Espanha',
    region: 'Nacional', // Added region
    continent: 'Europa',
    category: 'raspadinha',
    aiGenerated: true,
    createdAt: Date.now() - 200000,
  },
  {
    id: '3',
    customId: 'RASP-US-889',
    frontUrl: 'https://placehold.co/800x600/1e3a8a/white?text=Lucky+7s',
    gameName: 'Lucky 7s',
    gameNumber: '777',
    releaseDate: '2024-01-15',
    size: '4x4in',
    values: '$1, $7, $77, $777',
    state: 'VOID',
    country: 'EUA',
    continent: 'América',
    category: 'raspadinha',
    aiGenerated: true,
    createdAt: Date.now() - 300000,
  },
  {
    id: '4',
    customId: 'RASP-IT-202',
    frontUrl: 'https://placehold.co/600x600/065f46/white?text=Turista+per+Sempre',
    gameName: 'Turista per Sempre',
    gameNumber: '304',
    releaseDate: '2021-08-20',
    size: '12x18cm',
    values: '5€, 10€, 200€, 50.000€',
    state: 'CAMPIONE',
    country: 'Itália',
    continent: 'Europa',
    category: 'raspadinha',
    aiGenerated: true,
    createdAt: Date.now() - 400000,
  },
  {
    id: '5',
    customId: 'RASP-JP-999',
    frontUrl: 'https://placehold.co/500x500/7c2d12/white?text=Anime+Scratch',
    gameName: 'Anime Scratch',
    gameNumber: '101',
    releaseDate: '2023-12-01',
    size: '10x10cm',
    values: '¥100, ¥500, ¥10000',
    state: 'MINT',
    country: 'Japão',
    continent: 'Ásia',
    category: 'raspadinha',
    aiGenerated: true,
    createdAt: Date.now() - 50000,
  },
  // Add a specific Germany example with a region to demo the feature immediately
  {
    id: '6',
    customId: 'RASP-DE-001',
    frontUrl: 'https://placehold.co/600x600/eab308/black?text=Bayern+Gluck',
    gameName: 'Bayern Glück',
    gameNumber: '101',
    releaseDate: '2023-01-01',
    size: '10x10cm',
    values: '5€',
    state: 'MINT',
    country: 'Alemanha',
    region: 'Baviera',
    continent: 'Europa',
    category: 'raspadinha',
    aiGenerated: true,
    createdAt: Date.now() - 10000,
  }
];